### ISSUE TITLE
This user does not have the proper permissions for this action. Please sign in with a valid user credentials.

### ISSUE THREAD

**Issue by vinayakrathore** [OfficeDev/microsoft-teams-apps-faqplus#83] opened 2020-12-19 16:02 UTC
getting blow issue
This user does not have the proper permissions for this action. Please sign in with a valid user credentials.

**Comment by michaelwechner** [comment] 2021-01-12 23:46
I get the same error message when trying to login to my configuration webapp

https://wyonafaqplus-config.azurewebsites.net

whereas I followed all the steps according to the deployment guide. Any idea what I might be doing wrong? Thanks, Michael

**Comment by kozziag** [comment] 2021-01-23 04:43
> I get the same error message when trying to login to my configuration webapp
> 
> https://wyonafaqplus-config.azurewebsites.net
> 
> whereas I followed all the steps according to the deployment guide. Any idea what I might be doing wrong? Thanks, Michael

Are you using live/Hotmail account to login? The issue is with UPN potentially. I had the same issue. I was able to resolve it by following this: https://github.com/OfficeDev/microsoft-teams-apps-faqplus/issues/23

**Comment by michaelwechner** [comment] 2021-01-23 12:34
> > I get the same error message when trying to login to my configuration webapp
> > https://wyonafaqplus-config.azurewebsites.net
> > whereas I followed all the steps according to the deployment guide. Any idea what I might be doing wrong? Thanks, Michael
> 
> Are you using live/Hotmail account to login? The issue is with UPN potentially. I had the same issue. I was able to resolve it by following this: #23

Thanks for your feedback! No, I am using my own private email with the domain @wyona.com

I just deleted now the whole resource group which was created for FAQ Plus, because Azure charged between USD 5 -10 per day just to have the required services up andd running, but without actually being able to use them. I am not sure whether I made a mistake during setup, but anyway I think it would be good to have a note/warning to make people aware about the expected costs.

**Comment by v-smahaj** [comment] 2021-05-15 18:48
Solution of this issue is already provided in following link: #23 

Closing the issue. Please re-open if issue still persists.

**Closed by v-smahaj** 2021-05-15 18:48 UTC
