### ISSUE TITLE
Only able to assign to myself 

### ISSUE THREAD

**Issue by jeffswillbejeffs** [OfficeDev/microsoft-teams-apps-faqplus#162] opened 2022-03-10 14:53 UTC
Is there a reason that TEAM member can only assign the questions to themselves? Why can 't we assign them to other Team members part of the experts TEAM?

**Comment by Porkai-Pandian** [comment] 2022-03-16 19:01
Hi @jeffswillbejeffs,

This is by design that anyone from expert team can assign the question to themselves and start working on it with the user.

**Comment by jeffswillbejeffs** [comment] 2022-04-08 16:55
I have a customer who wish to you this bot and they want to be able to assign the question to any SME who is a member of that expert Team/group.

**Comment by gsv022** [comment] 2022-10-06 08:13
Hi @jeffswillbejeffs ,
Thanks for the suggestion. We will discuss this with our internal team and do the necessary. We are closing this request as the we have provided the inputs for the query raised. If you face any issue with FAQ-Plus please raise a new issue for further assistance.

**Closed by gsv022** 2022-10-06 08:13 UTC
Labels: answered
