### ISSUE TITLE
Config app is blank

### ISSUE THREAD

**Issue by Brennan-Richards** [OfficeDev/microsoft-teams-apps-faqplus#167] opened 2022-04-13 15:17 UTC
The message below shows up when I visit the config app, currently 40 minutes after deploying:

Your web app is running and waiting for your content

Your web app is live, but we don’t have your content yet. If you’ve already deployed, it could take up to 5 minutes for your content to show up, so come back soon.

How can I reconcile this?

**Comment by Brennan-Richards** [comment] 2022-04-13 15:18
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/51392895/163213751-0792863a-8672-430f-9804-1e8c7e0edcf5.png">

**Comment by Brennan-Richards** [comment] 2022-04-14 14:21
The config app still shows the same screen: 'Your web app is running and waiting for your content'.

**Comment by Brennan-Richards** [comment] 2022-04-14 15:46
Some logs from my latest attempt to sync the Azure Web App with the FAQ Plus Github repository...

Command: deploy.cmd
Handling .NET Web Application deployment.
Using Msbuild from 'C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin'.
All packages listed in packages.config are already installed.
  
  Restore operation started...
  
  6 libraries restored in 8.08 seconds
  
C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj : error : Version 3.1.417 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
Failed exitCode=1, command="C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin\MSBuild.exe" "C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="C:\local\Temp\8da1e2d2dcbfd9b";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="C:\home\site\repository\Source\\"
An error has occurred during web site deployment.
\r\nC:\Program Files (x86)\SiteExtensions\Kudu\96.40113.5578\bin\Scripts\starter.cmd deploy.cmd

**Comment by magurrapu** [comment] 2022-04-14 17:47
@Brennan-Richards Please let us know your availability to troubleshoot over call. Please also share your email id.

**Comment by Brennan-Richards** [comment] 2022-04-19 12:53
I'm noticing this sequence of logs when I run the `deploy.ps1`:

`Update reply urls...`

`ERROR: Forbidden({"ClassName":"Microsoft.Portal.Framework.Exceptions.ClientException","Message":"Graph call failed with httpCode=Forbidden, errorCode=Authorization_RequestDenied, errorMessage=This operation can only be performed by an administrator. Sign out and sign in as an administrator or contact one of your organization's administrators., reason=Forbidden, correlationId = 149ce79e-4f7b-4df5-840b-efea105d1f7d, response = {\"odata.error\":{\"code\":\"Authorization_RequestDenied\",\"message\":{\"lang\":\"en\",\"value\":\"This operation can only be performed by an administrator. Sign out and sign in as an administrator or contact one of your organization's administrators.\"},\"requestId\":\"b970f95b-15cc-4fd2-a584-6cf688d86e3b\",\"date\":\"2022-04-18T15:53:30\"}}","Data":{},"HResult":-2146233088,"XMsServerRequestId":null,"Source":null,"HttpStatusCode":403,"ClientData":{"errorCode":"Authorization_RequestDenied","localizedErrorDetails":{"errorDetail":"This operation can only be performed by an administrator. Sign out and sign in as an administrator or contact one of your organization's administrators."},"operationResults":null,"timeStampUtc":"2022-04-18T15:53:30.083181Z","clientRequestId":"149ce79e-4f7b-4df5-840b-efea105d1f7d","internalTransactionId":"2693906c-f284-4140-8f63-cca8961c683e","tenantId":null,"userObjectId":"ecf1ddcd-1849-4fc4-b910-a47b3edc20a4","exceptionType":"AADGraphException"}})`

`Waiting for admin consent to finish...`

`Current user does not have the privilege to consent the "User.Read" permission on this app. Please ask your tenant administrator to consent.`

The last bit of the error message, `"exceptionType":"AADGraphException"`, makes me think it could be related to the deprecation of AAD Graph per this article: https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions ...

**Comment by rmerino06** [comment] 2022-04-21 02:03
> In my case the deployment didn't finish correctly. Two resources shows me the status "Conflict" 

![image](https://user-images.githubusercontent.com/71419554/164356773-6381e9c5-8dfb-4a97-bb51-dc733d867656.png)

Any idea? in the error logs doesn't show much information

**Comment by Brennan-Richards** [comment] 2022-04-27 17:20
The same problem is occurring for me @rmerino06. It seems to be a problem with the repository's code.

Is there a Microsoft dev who can assist us with this issue?

<img width="728" alt="image" src="https://user-images.githubusercontent.com/51392895/165583018-8f30a2bb-bec3-4d72-a12a-2f2ba447db39.png">

My logs from the deployment center of the config app are as follows:

`Command: deploy.cmd
Handling .NET Web Application deployment.
Using Msbuild from 'C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin'.
All packages listed in packages.config are already installed.
  
  Restore operation started...
  
  6 libraries restored in 1.38 seconds
  
C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj : error : Version 3.1.417 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
C:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.Common\Microsoft.Teams.Apps.FAQPlusPlus.Common.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
Failed exitCode=1, command="C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin\MSBuild.exe" "C:\home\site\repository\Source\Microsoft.Teams.Apps.FaqPlusPlus.Configuration\Microsoft.Teams.Apps.FaqPlusPlus.Configuration.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="C:\local\Temp\8da286f25652fda";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="C:\home\site\repository\Source\\"
An error has occurred during web site deployment.
\r\nC:\Program Files (x86)\SiteExtensions\Kudu\97.40413.5690\bin\Scripts\starter.cmd deploy.cmd`

**Comment by AAdamCCox** [comment] 2022-04-27 20:42
@magurrapu I'm getting the same error here as reported by rmerino6, and both the function app and config app are blank. I tried adding dependsOn entries for each of them, which did force those two deployment tasks to run in series instead of in parallel. But the outcome was still the same; failed with a 'Conflict' error.
The Git source is present and shows failed, and a manual sync also fails.

**Comment by Brennan-Richards** [comment] 2022-04-28 16:14
@rmerino06 @AAdamCCox After a quick Google search, [this article](https://developercommunity.visualstudio.com/t/net-coremsbuild-tooling-not-finding-right-version/1145815) seems to describe the issue occurring in my error logs. Do your logs show something similar?

Going to try to edit the source code to resolve this issue going forward.

**Comment by Porkai-Pandian** [comment] 2022-04-28 16:27
@Brennan-Richards @rmerino06 thank you for bringing up the issue, yes the MSBuild version used is outdated, we working on fixing this across app templates and testing it, will soon release the fix to GitHub, apologize for the inconvenience.

**Comment by Brennan-Richards** [comment] 2022-04-29 12:18
@Porkai-Pandian Thank you!

**Comment by Porkai-Pandian** [comment] 2022-04-29 16:44
Thank you all for your patience, the fix will be released on Monday (2nd May 2022) for this repo.

**Comment by Porkai-Pandian** [comment] 2022-05-03 01:32
@Brennan-Richards @rmerino06 @AAdamCCox fix is released, please validate and let us know if the issue is resolved.

**Comment by Brennan-Richards** [comment] 2022-05-03 15:49
Can confirm that this worked for me as well. Thank you @Porkai-Pandian!

**Comment by Porkai-Pandian** [comment] 2022-05-03 16:12
Thanks for the confirmation, we're closing the issue, in case of any other issues, please open new one.

**Closed by Porkai-Pandian** 2022-05-03 16:12 UTC
Labels: answered
